import {assetUrl,STATIC_DEMO} from './assets.mjs';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,History,Search,Trash2,Volume2,Download,Film,RotateCcw,BookOpen,LoaderCircle,Settings2,ChevronRight} from 'lucide-react';
import VisualIcon from './VisualIcon';
import {Mark} from './art';
import Entry from './Entry';
import TutorialOverlay from './TutorialOverlay';
import TutorialPractice from './TutorialPractice';
import RoleSwitcher from './RoleSwitcher';
import HelperHome from './HelperHome';
import HelperGuidance from './HelperGuidance';
import OriginalMessages from './OriginalMessages';
import SaveRecordAction from './SaveRecordAction';
import Illustration from './Illustration';
import LanguagePicker from './LanguagePicker';
import DemoCases from './DemoCases';
import Compose from './Compose.jsx';
import {demoCompositions} from './demo-compositions.mjs';
import {caseImage,preloadDemoCases} from './demo-assets.mjs';
import NarratorDock from './NarratorDock';
import ElderControls from './ElderControls';
import ExportPanel from './ExportPanel';
import {ContentHeading,GentleVideo,NarratedText,ReadButton,SlowControls,useNarrator} from './Playback';
import {SourcePictures} from './ScreenshotPreview';
import FunctionSpeaker,{FunctionVoiceContext} from './FunctionSpeaker';
import ReadingPreparation,{CaptureSteps} from './ReadingPreparation';
import {contentNarrations} from './narration.mjs';
import {api,prepareImage} from './api.mjs';
import {allRecords,saveRecord,removeRecord,seedDemoRecords} from './history.mjs';
import {findRecords,validateFiles,id} from './domain.mjs';
import {loadSession,saveSession,entryStep,FONT_SIZES,narratedText} from './preferences.mjs';
import {getDemoResult,localResult} from './demo.mjs';
import {t,sourceName} from './i18n.mjs';
function resetScroll(){window.scrollTo({top:0});for(const node of document.querySelectorAll('.phone>main,.entry-shell'))node.scrollTop=0;}
function Notice({children,error=false}){return children?<div className={'notice '+(error?'error':'')} role={error?'alert':'status'}>{children}</div>:null;}
export default function App({initialSession}={}){
 const [session,setSession]=useState(()=>initialSession||loadSession()),[page,setPage]=useState('home'),[records,setRecords]=useState([]),[record,setRecord]=useState(null),[images,setImages]=useState([]),[source,setSource]=useState('auto');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[undo,setUndo]=useState(null),[edit,setEdit]=useState(null),[status,setStatus]=useState({henan:false}),[resultBusy,setResultBusy]=useState(false),[demoInput,setDemoInput]=useState(null),[casePurpose,setCasePurpose]=useState('browse');
 const [tourOpen,setTourOpen]=useState(initialSession?.experience==='first'),[tourScene,setTourScene]=useState(null);const appRoot=useRef(null);
 const input=useRef(null),translationVersion=useRef(0);const {mode,language,fontLevel,rate}=session;const elder=mode==='self',step=entryStep(session),L=key=>t(key,language);const narrator=useNarrator({language,rate});
 function updateSession(patch){narrator.stop();if(patch.experience!==undefined)setTourOpen(patch.experience==='first');else if(patch.mode!==undefined||patch.loggedIn===false)setTourOpen(false);const next={...session,...patch};setSession(next);try{saveSession(next);}catch{setError('本机没有保存设置；这次使用仍可继续。');}if(patch.mode!==undefined||patch.experience!==undefined){setPage('home');setRecord(null);setQuery('');setFilter('all');setEdit(null);setUndo(null);setImages([]);setError('');setNotice('');}}
 function setRate(value){const next={...session,rate:value};setSession(next);try{saveSession(next);}catch{}}
 useEffect(()=>{preloadDemoCases();},[]);
 useEffect(()=>{resetScroll();},[step]);
 useEffect(()=>{api('/status').then(setStatus).catch(()=>{});},[]);
 useEffect(()=>{if(!session.loggedIn)return;let alive=true;seedDemoRecords().then(allRecords).then(rows=>{if(alive)setRecords(rows);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[session.loggedIn]);
 async function persist(value){await saveRecord(value);setRecords(rows=>[value,...rows.filter(r=>r.id!==value.id)]);return value;}
 function go(next){if(busy||resultBusy)return;narrator.stop();setError('');setNotice('');setEdit(null);setPage(next);resetScroll();}
 const result=record?localResult(record,language):null;const reading=result?contentNarrations(result,language):null;
 useEffect(()=>{const mine=++translationVersion.current;if(!record||!['read','export'].includes(page)||localResult(record,language))return;setResultBusy(true);setError('');api('/analyze',{images:[],sourceType:record.sourceType==='unknown'?'auto':record.sourceType,correctedItems:record.items,language}).then(async({result:translated})=>{if(mine!==translationVersion.current)return;const next={...record,translations:{...record.translations,[language]:translated}};setRecord(next);try{await persist(next);}catch(e){setError(e.message);}}).catch(e=>{if(mine===translationVersion.current)setError(e.message);}).finally(()=>{if(mine===translationVersion.current)setResultBusy(false);});return()=>{translationVersion.current++;};},[record?.id,language,page]);
 async function chooseFiles(event){setError('');const files=Array.from(event.target.files||[]);if(!files.length)return;try{validateFiles(files);setBusy(true);setImages(await Promise.all(files.map(prepareImage)));setDemoInput(null);setSource('auto');}catch(e){setError(e.message);}finally{setBusy(false);event.target.value='';}}
 async function analyze(correctedItems){
  narrator.stop();setBusy(true);setError('');
  if(!correctedItems){setPage('processing');resetScroll();if(demoInput)return;}
  try{
   const {result:value}=await api('/analyze',{images:correctedItems?[]:images,sourceType:correctedItems?(record.sourceType==='unknown'?'auto':record.sourceType):source,language,...(correctedItems?{correctedItems}:{})});
   const next={...value,id:correctedItems?record.id:id(),caseId:correctedItems?record.caseId:undefined,account:'family-demo',mode,images:correctedItems?record.images:images,createdAt:correctedItems?record.createdAt:new Date().toISOString(),sample:correctedItems?Boolean(record.sample):false,sampleGenerated:correctedItems?Boolean(record.sample):false,language,translations:{[language]:value}};
   setRecord(next);setEdit(null);setPage('read');try{await persist(next);setNotice(L('saved'));}catch(e){setError(e.message);}resetScroll();
  }catch(e){setError(e.message);if(!correctedItems)setPage('upload');}finally{setBusy(false);}
 }
 async function finishDemo(){
  if(!demoInput)return;
  narrator.stop();const next={...demoInput,images,createdAt:new Date().toISOString()};setRecord(next);setPage('read');setBusy(false);setEdit(null);resetScroll();
  try{await persist(next);setNotice(L('saved'));}catch(e){setError(e.message);}
 }
 function openCases(purpose='browse'){setCasePurpose(purpose);go('cases');}
 function selectCase(row){
  if(casePurpose!=='import'){openRecord(row);return;}
  setDemoInput(row);setImages([{dataUrl:caseImage(row.caseId),name:row.title}]);setSource(row.sourceType);go('upload');
 }

 function openRecord(row){setRecord(row);go('read');}
 async function remove(row){try{await removeRecord(row.id);setRecords(rs=>rs.filter(r=>r.id!==row.id));setUndo(row);setNotice(L('removed'));}catch(e){setError(e.message);}}
 async function restore(){try{await persist(undo);setUndo(null);setNotice(L('restored'));}catch(e){setError(e.message);}}
 const currentRows=findRecords(records,{mode,query,source:filter});
 const titles={compose:'给爸妈写几句话',upload:elder?L('uploadTitle'):'把发过的消息讲明白',history:L(elder?'history':'helperHistory'),processing:'这段话，慢慢讲给您听',cases:casePurpose==='import'?'演示相册':L('examples'),read:elder?L('readPage'):'给爸妈看的解释',export:L('export'),settings:elder?L('settings'):'偏好设置',help:L('help'),video:L('videoTitle')};
 const disabled=busy||resultBusy;
 function languageButtons(){return <LanguagePicker value={language} onChange={value=>updateSession({language:value})} disabled={disabled} label="" variant={elder?'elder':'compact'}/>;}
 function startExplanation(){setImages([]);setDemoInput(null);setSource('auto');go('upload');}
 function startUpload(){setImages([]);setDemoInput(null);setSource('auto');go(elder?'upload':'compose');}
 async function createComposition(value){narrator.stop();setError('');setNotice('');setRecord(value);setPage('export');resetScroll();try{await persist(value);}catch(e){setError(e.message);}}
 function DemoTools(){return <details className="demo-tools"><summary>{L('demoTools')} · {L(elder?'elderMode':'helperMode')}</summary><p>{L('demoAccount')}</p><div><button disabled={disabled} onClick={()=>updateSession({mode:null,experience:null})}>{L('changeRole')}</button><button disabled={disabled} onClick={()=>updateSession({loggedIn:false,mode:null,experience:null})}>{L('reopenLogin')}</button><button disabled={disabled} onClick={()=>openCases('import')}>{L('examples')}</button>{!STATIC_DEMO&&page==='upload'&&<button disabled={disabled} onClick={()=>input.current?.click()}>使用本机截图（实际识别）</button>}{!STATIC_DEMO&&<a href="http://localhost:4173/" target="_blank" rel="noreferrer">{L('keepOld')}</a>}</div><p>{L('testPictures')}</p><p>{L('testPictureNote')}</p><div>{[['W1','wechat'],['S1','sms'],['P3','moments']].map(([file,key])=><a key={file} href={assetUrl('/demo-cases/'+file+'.png')} download>{L(key)}</a>)}</div></details>;}
 if(step!=='ready')return <Entry step={step} session={session} onChange={updateSession} onBack={()=>updateSession(step==='experience'?{languageChosen:false,experience:null}:step==='language'?{mode:null,languageChosen:false,experience:null}:{loggedIn:false,mode:null,languageChosen:false,experience:null})}/>;
 function startTutorial(){narrator.stop();setPage('home');setTourScene(null);setTourOpen(true);}
 function closeTutorial(){narrator.stop();setTourOpen(false);setTourScene(null);setPage('home');}
 function showTutorialStep(item){setTourScene(item.scene||null);}
 return <FunctionVoiceContext.Provider value={elder?{narrator,language}:null}><div ref={appRoot} className={'app-shell '+(elder?'elder font-'+fontLevel:'helper')} style={{'--copy-size':(elder?FONT_SIZES[fontLevel]:17)+'px','--ui-size':(elder?[22,24,28,32][fontLevel]:16)+'px'}}><div className="desktop-top"><span><Mark/>家里话 <small>{L(elder?'elderMode':'helperMode')}</small></span><span className="demo-badge">DEMO</span></div><div className="phone"><header><div className="app-toolbar">{page==='home'?<span className="brand"><Mark/>家里话</span>:<button className="back" disabled={disabled} onClick={()=>go(page==='export'?'read':page==='cases'&&casePurpose==='import'?'upload':'home')}><ArrowLeft/>{L('back')}</button>}<RoleSwitcher mode={mode} language={language} disabled={disabled} onChange={value=>{updateSession({mode:value});resetScroll();}}/></div>{elder&&<ElderControls fontLevel={fontLevel} onFont={value=>updateSession({fontLevel:value})} rate={rate} onRate={setRate} language={language} onLanguage={value=>updateSession({language:value})} disabled={disabled}/>}</header><NarratorDock narrator={narrator} language={language}/><main>{tourOpen&&tourScene?<TutorialPractice scene={tourScene} mode={mode} language={language}/>:<><Notice error>{error}</Notice><Notice>{notice}</Notice>{undo&&<button className="quiet" onClick={restore}><RotateCcw/>{L('undo')}</button>}
 {page==='home'&&(elder?<><div className="elder-greeting"><p className="eyebrow">{L('elderGreeting')}</p><Illustration kind="elderHome" className="elder-home-art" eager/></div><div className="title-with-read" data-tour="speaker"><h1><NarratedText text={L('elderTitle')} narrator={narrator}/></h1><ReadButton title text={L('elderTitle')} language={language} narrator={narrator}/></div><div className="spoken-feature"><button className="hero-action green" data-tour="upload" onClick={startUpload}><span className="feature-art-frame"><Illustration kind="screenshot" eager/></span><span className="hero-content"><strong><NarratedText text={L('selectPicture')} narrator={narrator}/></strong><span>{L('selectPictureSub')}</span></span><ArrowRight/></button><ReadButton title text={L('selectPicture')} language={language} narrator={narrator}/></div><div className="spoken-feature"><button className="hero-action wheat" onClick={()=>go('history')}><span className="feature-art-frame"><Illustration kind="history" eager/></span><span className="hero-content"><strong><NarratedText text={L('history')} narrator={narrator}/></strong><span>{L('oldSub')}</span></span><ArrowRight/></button><ReadButton title text={L('history')} language={language} narrator={narrator}/></div><div className="function-action"><button data-tour="video" className="demo-example-link illustrated-link" onClick={()=>go('video')}><Illustration kind="video"/><span>{L('demoVideo')}</span><ChevronRight/></button><FunctionSpeaker id="video"/></div></>:<HelperHome language={language} records={records.filter(r=>r.mode===mode)} onUpload={startUpload} onHistory={()=>go('history')} onVideo={()=>go('video')} onRecord={openRecord} onCases={startExplanation}/>)}
 {page!=='home'&&<div className="title-with-read"><h1 className="page-title"><NarratedText text={titles[page]} narrator={narrator}/></h1>{elder&&(['upload','cases','processing','history','read','video','settings'].includes(page)?<FunctionSpeaker id={page==='upload'?(images.length?'preview':'upload'):page==='cases'?'album':page}/>:<ReadButton title text={titles[page]} language={language} narrator={narrator}/>)}</div>}
 {page==='compose'&&<Compose language={language} onCreate={createComposition} onCancel={()=>go('home')} examples={demoCompositions}/>}
 {page==='cases'&&<DemoCases mode={mode} language={language} onSelect={selectCase} importing={casePurpose==='import'} narrator={elder?narrator:null}/>}
 {page==='settings' &&<div className="preferences">{elder&&<section><h2>{L('font')}</h2><div className="font-options">{['font1','font2','font3','font4'].map((key,i)=><button aria-pressed={fontLevel===i} key={key} onClick={()=>updateSession({fontLevel:i})}><span aria-hidden="true" style={{fontSize:[22,26,30,34][i]}}>字</span>{L(key)}</button>)}</div><p className="font-preview">{L('fontPreview')}</p><ReadButton text={L('fontPreview')} language={language} narrator={narrator}/></section>}<section><h2>{L('language')}</h2>{languageButtons()}<p className="fine">{L(language==='henan'?'voiceHenan':'voiceMandarin')}</p>{language==='henan'&&!status.henan&&<Notice>{L('voiceUnavailable')}</Notice>}</section>{elder&&<section><h2>{L('voiceInfo')}</h2><SlowControls rate={rate} onRate={setRate} language={language}/><button className="secondary" onClick={()=>narrator.speak(L('fontPreview'),L('voiceInfo'))}><Volume2/>{L('read')}</button></section>}{!elder&&<p className="fine">这里选择界面和默认配音。给家人的长图和视频，也可以在导出时单独选普通话或河南话。</p>}<button className="primary" onClick={()=>go('home')}>{L('done')}</button></div>}
 {page==='upload'&&<>
  <CaptureSteps step={0}/><p className="intro">{elder?(language==='henan'?'先挑张图，再让俺讲讲。':'先选一张图，再帮您讲明白。'):'选一张已经发出的微信、朋友圈或短信截图，整理成爸妈容易理解的话。'}</p>
  <input ref={input} type="file" accept="image/png,image/jpeg,image/webp" multiple hidden onChange={chooseFiles}/>
  {images.length>0?<><SourcePictures images={images.map((image,index)=>({src:image.dataUrl,alt:'已选择的截图 '+(index+1)}))} language={language}/>{demoInput&&<p className="sample-tag">{L('sample')} · {demoInput.title}</p>}<button className="secondary" disabled={busy} onClick={()=>openCases('import')}>{L('rechoose')}</button></>:<button className="upload-area" disabled={busy} onClick={()=>openCases('import')}><span className="feature-art-frame"><Illustration kind="screenshot" eager/></span><strong>{L('chooseAlbum')}</strong><span>{L('imageKinds')}</span></button>}
  <p className="fine">演示相册里已备好 9 张截图。</p>
  {images.length>0&&<label className="field"><span className="function-label">{L('sourceQuestion')}<FunctionSpeaker id="source"/></span><select value={source} onChange={e=>setSource(e.target.value)} disabled={busy||Boolean(demoInput)}>{['auto','wechat_chat','sms','moments'].map(value=><option key={value} value={value}>{sourceName(value,language)}</option>)}</select></label>}
  <div className="function-action"><button className="primary" disabled={!images.length||busy} onClick={()=>analyze()}>{busy?<LoaderCircle/>:<BookOpen/>}{busy?L('analyzing'):elder?L('analyze'):'整理给爸妈看'}</button><FunctionSpeaker id="analyze"/></div>
  {images.length>0&&<p className="fine">{demoInput?'这张演示图片的解释已提前准备。':L('uploadPrivacy')}</p>}
 </>}
 {page==='processing'&&<><CaptureSteps step={1}/><ReadingPreparation demo={Boolean(demoInput)} image={images[0]?.dataUrl} language={language} onReady={finishDemo}/></>}

 {page==='history'&&<><p className="intro">{L(page==='cases'?'exampleNote':'oldSub')}</p><label className="search"><Search/><input placeholder={L('search')} value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filters">{[['all','all'],['wechat_chat','wechat'],['moments','moments'],['sms','sms']].map(([value,key])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{L(key)}</button>)}</div><div className="function-label"><p className="fine">{L('recordsNote')}</p><FunctionSpeaker id="filters"/></div>{currentRows.filter(r=>page!=='cases'||r.sample).length?currentRows.filter(r=>page!=='cases'||r.sample).map(row=><article className="history-row" key={row.id}><SourcePictures record={row} language={language} compact/><button className="history-open" onClick={()=>openRecord(row)}><span className="record-icon"><VisualIcon kind={row.sourceType==='sms'?'mail':'image'}/></span><span><small>{row.sourceKind==='composition'?'写给家人的话':sourceName(row.sourceType,language)}{row.sample?' · '+L('sample'):''}</small><strong>{localResult(row,language)?.title||row.title}</strong></span><ArrowRight/></button>{elder&&<ReadButton title text={localResult(row,language)?.title||row.title} language={language} narrator={narrator}/>}<button className="remove" aria-label={L('remove')+'：'+row.title} onClick={()=>remove(row)}><Trash2/>{L('remove')}</button></article>):<div className="empty illustrated-empty"><Illustration kind="empty"/><h3>{L('noRecords')}</h3><p>{L('trySearch')}</p><button className="secondary" onClick={startUpload}>{L('selectPicture')}</button></div>}</>}
 {resultBusy&&<Notice>{L('translating')}</Notice>}
 {page==='read'&&record&&result&&<fieldset className="reading-content" disabled={disabled}><SourcePictures record={record} language={language}/><div className="source-meta"><span>{sourceName(record.sourceType,language)}</span><span>{record.sourceKind==='composition'?'我写给家人的话':record.sample?L('sample')+' · '+L(record.sampleGenerated?'ai':'prepared'):L('ai')}</span></div><article className="reading-card"><p className="eyebrow">{L('thisSays')}</p><ContentHeading title={result.title} text={reading.all} narrator={elder?narrator:null} language={language} whole/><div className="plain-copy">{result.explanation.split('\n').filter(Boolean).map((line,i)=><div className="readable-paragraph" key={i}><p><NarratedText text={line} narrator={narrator} context={result.explanation}/></p>{elder&&<ReadButton text={line} language={language} narrator={narrator}/>}</div>)}</div></article>{result.glossary?.length>0&&<section className="glossary"><ContentHeading title={L('terms')} text={reading.terms} narrator={elder?narrator:null} language={language}/>{result.glossary.map((term,i)=><div key={i}><strong><NarratedText text={term.term} narrator={narrator} context={term.term+'。'+term.explanation}/></strong><p><NarratedText text={term.explanation} narrator={narrator} context={term.term+'。'+term.explanation}/></p>{elder&&<ReadButton text={term.term+'。'+term.explanation} language={language} narrator={narrator}/>}</div>)}</section>}{!elder&&<HelperGuidance result={result} record={record}/>}<OriginalMessages key={record.id} items={record.items} language={language} narrator={elder?narrator:null}/>{!record.sample&&record.sourceKind!=='composition'&&(edit?<section className="edit-block"><h2>{L('checkOriginal')}</h2>{edit.map((item,i)=><div key={i}><label className="field">{L('speaker')}<input value={item.speaker} onChange={e=>setEdit(rows=>rows.map((r,n)=>n===i?{...r,speaker:e.target.value}:r))}/></label><label className="field">{L('sourceText')}<textarea rows={3} value={item.text} onChange={e=>setEdit(rows=>rows.map((r,n)=>n===i?{...r,text:e.target.value}:r))}/></label></div>)}<button className="primary" disabled={busy||edit.some(i=>!i.text.trim())} onClick={()=>analyze(edit)}>{L(busy?'analyzing':'reinterpret')}</button><button className="secondary" disabled={busy} onClick={()=>setEdit(null)}>{L('cancel')}</button></section>:<button className="quiet" onClick={()=>setEdit(record.items.map(i=>({...i})))}>{L('editOriginal')}</button>)}<div className="reading-actions"><SaveRecordAction key={record.id} language={language} onSave={()=>persist(record)}/>{!elder&&<button className="primary" onClick={()=>go('export')}><Film/>{L('export')}</button>}</div></fieldset>}
 {page==='export'&&record&&result&&<ExportPanel key={record.id+'-'+language} record={record} result={result} language={language} onSave={async value=>{await persist(value);setRecord(value);}} onWorking={setBusy} rate={rate} onRate={setRate} narrator={narrator} henanReady={status.henan}/>}
 {page==='video'&&<><SourcePictures record={{...getDemoResult('P3',language),caseId:'P3',sample:true}} language={language}/><p className="intro">{L('demoVideoSub')}</p><p className="sample-tag">{L('sample')} · {L('voiceInfo')}</p>{language==='henan'&&!status.henanDemo?<Notice>{L('voiceUnavailable')}</Notice>:<><GentleVideo src={`/demo/P3-${language}.mp4`} poster="/demo/P3-poster.png" language={language} rate={elder?rate:1} onRate={setRate} onPlay={narrator.stop} compact={!elder}/><a className="secondary" href={assetUrl(`/demo/P3-${language}.mp4`)} download={`家里话-饺子与想念-${language}.mp4`}><Download/>{L('saveVideo')}</a></>}<p className="fine">{L('exampleNote')}</p></>}
 {page==='help'&&<button className="primary" onClick={startTutorial}>开始使用教程</button>}
 {page==='home'&&<div className="function-action"><button className="tutorial-entry" onClick={startTutorial}><BookOpen aria-hidden="true"/>再看使用教程</button><FunctionSpeaker id="tutorial"/></div>}<DemoTools/></>}</main><nav className="primary-nav" aria-label="主要功能"><button aria-current={page==='home'?'page':undefined} disabled={disabled} onClick={()=>go('home')}><VisualIcon kind="home"/><span>{elder?L('home'):'家里话'}</span></button><button data-tour="history" aria-current={page==='history'?'page':undefined} disabled={disabled} onClick={()=>go('history')}><History/><span>{elder?L('history'):'我的作品'}</span></button>{!elder&&<button data-tour="settings" aria-current={page==='settings'?'page':undefined} disabled={disabled} onClick={()=>go('settings')}><Settings2/><span>偏好</span></button>}</nav></div></div>{tourOpen&&<TutorialOverlay key={mode} mode={mode} language={language} rate={rate} fontLevel={fontLevel} backgroundRef={appRoot} onClose={closeTutorial} onStepChange={showTutorialStep}/>}</FunctionVoiceContext.Provider>;
}
