const row=(speaker,text,kind='message')=>({speaker,text,kind});
export const cases=[
 {id:'W1',sourceType:'wechat_chat',title:'姥姥，我答辩通过啦',theme:'听懂孩子的喜讯',why:'把“答辩、上岸”讲明白，让长辈知道孩子在高兴什么。',items:[row('外孙女晓晓','姥姥，我今天毕业论文答辩过啦！这关终于上岸了😭'),row('外孙女晓晓','周六回家，想吃您包的饺子。')],explanation:'晓晓说，她今天通过了毕业论文答辩。\n她说“这关上岸了”，是说这件盼望完成的事终于办成了。\n她打算周六回家，想吃姥姥包的饺子。',glossary:[{term:'答辩',explanation:'向老师说明自己的论文，并回答老师的问题。'},{term:'上岸',explanation:'这里指通过了答辩，不是去水边。'}],uncertainties:['截图没有写周六的具体日期。'],recommend:true},
 {id:'W2',sourceType:'wechat_chat',title:'孩子说emo，是怎么了',theme:'读懂表达，少一点误会',why:'解释网络词，但不把一句话诊断成疾病，也不替孩子编造心事。',items:[row('外孙女晓晓','这两天有点emo，事情没做好。'),row('外孙女晓晓','我没生病，周末想自己安静歇一歇，下周再和您视频。')],explanation:'晓晓说，这两天因为事情没做好，心情有些低落。\n她明确说自己没生病。周末想安静休息，下周再和您视频。',glossary:[{term:'emo',explanation:'这里是说心情低落。这个词本身不代表一种疾病。'}],uncertainties:['没有说明哪件事没做好，也没有确定视频通话时间。']},
 {id:'W3',sourceType:'wechat_chat',title:'周五不回，改成周日',theme:'多条消息合起来才明白',why:'保留改期、金额和“不要”，避免长辈只看到群里的一句话。',items:[row('儿子小军','妈，我周五不回去了，改成周日。'),row('儿子小军','车票249元，已经买好了，不用给我转钱。'),row('儿子小军','到家前我给您打电话，您别去车站接。')],explanation:'小军改了回家的时间：周五不回来，改成周日。\n249元的车票他已经买好，不用给他转钱。\n他到家前会打电话，让妈妈不要去车站接。',glossary:[],uncertainties:['没有写周日的具体到达时间。']},
 {id:'P1',sourceType:'moments',title:'转正了，评论也得分清',theme:'跟上孩子的生活',why:'区分朋友圈正文与评论，不能把朋友的玩笑当成孩子的消息。',items:[row('晓晓','入职三个月，今天终于转正啦！','post'),row('阿圆','恭喜！下回请奶茶！','comment'),row('晓晓','好呀，周末约。','reply')],explanation:'晓晓说，她入职三个月，今天已经通过试用期，成为正式员工。\n朋友阿圆在评论里祝贺她，还约她请奶茶。晓晓回复说周末约。',glossary:[{term:'转正',explanation:'这里指通过工作试用期，成为正式员工。'}],uncertainties:['没写工作的单位，也没写聚会地点。']},
 {id:'P2',sourceType:'moments',title:'孩子拿了PB，是什么奖',theme:'让长辈参与小小的骄傲',why:'解释运动缩写，避免把“个人最好”误说成全校第一。',items:[row('外孙小满','校运会800米跑出PB！比上次快了12秒，给自己点个赞。','post'),row('妈妈','坚持训练没白费，真棒！','comment')],explanation:'小满参加校运会的800米跑步，比自己上次快了12秒。\n“PB”是他自己的最好成绩，不代表他得了全校第一。\n妈妈在评论里夸他坚持训练。',glossary:[{term:'PB',explanation:'个人最好成绩。'}],uncertainties:['没有写比赛名次，也没有写总用时。']},
 {id:'P3',sourceType:'moments',title:'一盒饺子，让孩子破防了',theme:'把关心接住',why:'用上下文解释“破防”，长辈无需懂网络词，也能接住孩子的想念。',items:[row('外孙女晓晓','收到姥姥寄的饺子，一开箱就破防了。突然特别想家。','post'),row('妈妈','吃完记得给姥姥打个电话。','comment')],explanation:'晓晓收到了姥姥寄来的饺子，看见后很受触动，突然特别想家。\n这里的“破防”是在说自己的情绪被触动了。\n妈妈在评论里提醒她，吃完给姥姥打电话。',glossary:[{term:'破防',explanation:'原本压着的情绪一下子涌出来。这里结合“想家”来理解。'}],uncertainties:['截图没有显示晓晓是否已经打过电话。'],recommend:true},
 {id:'S1',sourceType:'sms',title:'取件码再也不用到处翻',theme:'看懂一次，以后找得到',why:'放大数字、听清取件信息，并用历史搜索重新找到。',items:[row('10690000','【示例快递】尾号2816的包裹已到春风驿站。取件码7-249，保管至9月22日18:00。'),row('10690000','本次取件不收费，请勿向陌生人转账。')],explanation:'短信写着，尾号2816的包裹到了春风驿站。\n取件码：7-249。保管到9月22日18:00。\n短信写明，本次取件不收费，不要向陌生人转账。',glossary:[{term:'取件码',explanation:'取包裹时用来核对的一串号码。'}],uncertainties:['短信显示号码不等于身份已验证。','“尾号2816”具体是哪种号码的尾号，短信未说明。'],recommend:true},
 {id:'S2',sourceType:'sms',title:'活动改期，可别白跑一趟',theme:'一眼看到真正的变更',why:'把时间、楼层和否定分开，降低密密麻麻通知的阅读负担。',items:[row('社区通知','【春风社区·虚构示例】手工活动改至9月24日上午9:30，地点为社区服务中心2楼。不是原定的9月23日，活动不收报名费。')],explanation:'这条通知说，手工活动改到9月24日上午9:30。\n地点是社区服务中心2楼。\n不要按原来的9月23日去。通知说活动不收报名费。',glossary:[],uncertainties:['这里只转述短信，尚未核实发送方和活动。']},
 {id:'S3',sourceType:'sms',title:'流量提醒，不等于欠费',theme:'陌生概念讲得明白',why:'解释手机套餐术语，避免把提醒误解成已经扣钱或欠费。',items:[row('运营商提醒','【虚构套餐提醒】您本月套餐内流量已用8GB，剩余2GB。本短信仅提醒使用情况，未为您订购任何加油包。')],explanation:'短信说，本月套餐里的手机上网流量用了8GB，还剩2GB。\n短信明确说没有替您购买额外流量包。\n这条短信没有说您欠费，也没有要求您付款。',glossary:[{term:'流量',explanation:'这里是手机通过运营商网络上网时使用的额度。'},{term:'加油包',explanation:'这里指额外的流量套餐，不是汽车加油。'}],uncertainties:['短信没有写套餐用完后怎样收费。']}
];
export const caseGroups=[{sourceType:'wechat_chat',name:'微信聊天',prefix:'W',question:'哪段家人的话最值得讲明白？'},{sourceType:'moments',name:'朋友圈',prefix:'P',question:'长辈怎样参与孩子的日常？'},{sourceType:'sms',name:'短信',prefix:'S',question:'哪条日常信息最值得留下？'}];
