import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Heart,Check,Volume2,LoaderCircle} from 'lucide-react';
import {Mark} from './art';import Illustration from './Illustration';import {t} from './i18n.mjs';import {useNarrator} from './Playback';
import FunctionSpeaker,{FunctionVoiceContext} from './FunctionSpeaker';
import {entryAudio,entryNarrations} from './tutorial-content.mjs';
function VoiceChoice({session,onChange}){
 const elder=session.mode==='self';const [choice,setChoice]=useState(null);const narrator=useNarrator({language:session.language,rate:1}),voice=useRef(narrator);voice.current=narrator;
 useEffect(()=>{if(!elder)return;voice.current.speak(entryNarrations.question[session.language],'选择声音',entryAudio('question',session.language));return()=>voice.current.stop();},[]);
 function preview(language){narrator.stop();narrator.speak(entryNarrations.sample[language],'试听'+(language==='henan'?'河南话':'普通话'),entryAudio('sample',language));}
 return <><p className="entry-voice-intro">{elder?'先听一听，再选您喜欢的声音。':'为爸妈选择内容和视频的默认声音。'}</p><div className="entry-voice-choices" role="radiogroup" aria-label="更想听的语言">
  {[['mandarin','中文','普通话'],['henan','方言','河南话']].map(([value,title,sub])=><div className={'entry-voice-card'+(choice===value?' selected':'')} key={value}><label><input type="radio" name="entry-language" value={value} checked={choice===value} aria-label={title+' · '+sub} onChange={()=>{narrator.stop();setChoice(value);}}/><span><strong>{title}</strong><small>{sub}</small></span>{choice===value&&<Check aria-hidden="true"/>}</label>{elder&&<button className="voice-audition" onClick={()=>preview(value)} aria-label={'试听'+sub}><Volume2 aria-hidden="true"/>听听声音</button>}</div>)}
 </div><p className="voice-choice-note">方言目前提供河南话。<br/>{elder?'选好后，教程和页面朗读都用这个声音。':'子女教程使用文字引导。导出时也能调整声音。'}</p><div className="entry-voice-status" aria-live="polite">{narrator.status==='loading'?<><LoaderCircle aria-hidden="true"/>正在准备声音</>:narrator.status==='playing'?<><Volume2 aria-hidden="true"/>{narrator.label}<button onClick={narrator.stop}>停止试听</button></>:null}</div>{narrator.error&&<p className="notice error" role="alert">声音没放出来，请再点一次试听。</p>}<button className="primary language-confirm" disabled={!choice} onClick={()=>{narrator.stop();onChange({language:choice,languageChosen:true,experience:null});}}>就用这个声音<ArrowRight aria-hidden="true"/></button></>;
}
export default function Entry({step,session,onChange,onBack}){
 const lang=session.language,narrator=useNarrator({language:lang,rate:1}),voice=useRef(narrator);voice.current=narrator;
 const experience=step==='experience',elder=session.mode==='self';
 useEffect(()=>()=>voice.current.stop(),[step]);
 useEffect(()=>{if(!experience||!elder)return;voice.current.speak(entryNarrations.experience[lang],'使用前的小问题',entryAudio('experience',lang));return()=>voice.current.stop();},[experience,lang,elder]);
 function replay(){narrator.stop();narrator.speak(entryNarrations.experience[lang],'使用前的小问题',entryAudio('experience',lang));}
 return <FunctionVoiceContext.Provider value={{narrator,language:lang}}><div className={'entry-shell entry-'+step+(elder?' entry-elder':'')}><div className="entry-brand"><Mark/><span>家里话</span><small>JIALIHUA</small></div>{step!=='login'&&<div className="entry-progress"><button onClick={()=>{narrator.stop();onBack();}}><ArrowLeft aria-hidden="true"/>{t('back',lang)}</button><span>{{role:1,language:2,experience:3}[step]} / 3</span></div>}
 {step==='login'?<section className="welcome-card"><span className="welcome-stamp"><Heart/>一份懂得，一份关心</span><div className="entry-title-row"><h1>{t('welcome',lang)}</h1><FunctionSpeaker id="login"/></div><p className="welcome-copy">{t('welcomeSub',lang)}</p><div className="welcome-picture"><Illustration kind="welcome" eager/></div><div className="demo-login"><span className="account-seal"><Check/></span><div><strong>{t('demoAccount',lang)}</strong><p>{t('autoLogin',lang)}</p></div></div><button className="primary entry-start" onClick={()=>onChange({loggedIn:true,mode:null,languageChosen:false,experience:null})}>{t('start',lang)}<ArrowRight/></button><p className="entry-footnote">{t('demoOnly',lang)}</p></section>:<>
 <p className="eyebrow">{step==='role'?'先认识一下您':step==='language'?'让声音更亲切':'最后，了解一点'}</p><div className="entry-title-row"><h1 className="entry-question">{step==='language'?'更想听的语言':t(step==='role'?'roleQuestion':'experienceQuestion',lang)}</h1>{step==='role'&&<FunctionSpeaker id="role"/>}{experience&&elder&&<button className="entry-question-speaker" onClick={replay} aria-label="再听一遍这道题"><Volume2 aria-hidden="true"/></button>}</div>
 {step==='language'?<VoiceChoice session={session} onChange={onChange}/>:<><div className="entry-choices">{(step==='role'?[{value:'self',title:'roleSelf',sub:'roleSelfSub'},{value:'helper',title:'roleHelper',sub:'roleHelperSub'}]:[{value:'first',title:'first',sub:'firstSub'},{value:'used',title:'used',sub:'usedSub'}]).map((item,i)=><button key={item.value} className={'entry-choice choice-'+i} onClick={()=>{narrator.stop();onChange(step==='role'?{mode:item.value,languageChosen:false,experience:null}:{experience:item.value});}}><span className="choice-heading">{t(item.title,lang)}<ArrowRight/></span><span className="choice-picture"><Illustration kind={item.value} eager/></span><span className="choice-description">{experience?(item.value==='first'?'带我一步一步学怎么用':'我会用了，直接进入'):t(item.sub,lang)}</span></button>)}</div>{experience&&<><p className="entry-selected-voice">{elder&&<Volume2 aria-hidden="true"/>}{elder?'接下来用':'已选导出声音：'}{lang==='henan'?'河南话':'普通话'}{elder?'讲解':''}</p>{narrator.error&&<p className="notice error" role="alert">声音暂时没放出来，点小喇叭可以再听。</p>}</>}</>}
 <p className="entry-footnote">{t('demoAccount',lang)} · {t('noAutomaticLogin',lang)}</p></>}
 </div></FunctionVoiceContext.Provider>;
}
