import React,{useState} from 'react';
import {Check,ArrowRight,Headphones,FileText} from 'lucide-react';
import {cases,caseGroups} from './data.mjs';
import options from './voice-options.json';

function initial(){try{return JSON.parse(localStorage.getItem('jlh-v2-choices'))||{cases:{},voices:{}};}catch{return {cases:{},voices:{}};}}
export default function Selection({onTry,onBack}){
 const [tab,setTab]=useState('cases'),[selection,setSelection]=useState(initial),[notice,setNotice]=useState('');
 function choose(kind,key,value){const next={...selection,[kind]:{...selection[kind],[key]:value}};setSelection(next);try{localStorage.setItem('jlh-v2-choices',JSON.stringify(next));setNotice('已在本机标记选择。');}catch{setNotice('选择暂存于此页面，浏览器没有允许保存。');}}
 const voices=Array.isArray(options)?options:options.options||options.voices||[];
 return <div className="selection"><div className="selection-heading"><p className="eyebrow">家里话 · DEMO 选材室</p><h1>先选一段话，<br/>再选一种声音。</h1><p>案例先看文案；选定后再做截图素材。声音暂用普通话，不作为河南话效果。</p></div>
 <div className="segmented"><button aria-pressed={tab==='cases'} onClick={()=>setTab('cases')}><FileText/>九个案例</button><button aria-pressed={tab==='voices'} onClick={()=>setTab('voices')}><Headphones/>九版试听</button></div>
 {notice&&<p className="notice" role="status">{notice}</p>}
 {tab==='cases'?caseGroups.map(group=><section className="selection-group" key={group.prefix}><div className="group-heading"><span>{group.prefix}</span><div><h2>{group.name}</h2><p>{group.question}</p></div></div><div className="candidate-grid">{cases.filter(c=>c.sourceType===group.sourceType).map(c=><article className={'candidate '+(selection.cases[group.prefix]===c.id?'chosen':'')} key={c.id}><div className="candidate-top"><b>{c.id}</b><span>{c.theme}</span>{c.recommend&&<small>建议优先看</small>}</div><h3>{c.title}</h3><p className="candidate-why">{c.why}</p><div className="source-script">{c.items.map((item,i)=><div key={i}><strong>{item.speaker}{item.kind==='comment'?' · 评论':item.kind==='reply'?' · 回复':''}</strong><p>{item.text}</p></div>)}</div><details><summary>看看拟定的白话解释</summary><p className="keep-lines">{c.explanation}</p><p className="fine">虚构案例，解释预先编写，尚未生成对应截图。</p></details><div className="candidate-actions"><button className="primary" aria-pressed={selection.cases[group.prefix]===c.id} onClick={()=>choose('cases',group.prefix,c.id)}>{selection.cases[group.prefix]===c.id?<><Check/>已选 {c.id}</>:<>选 {c.id}</>}</button><button className="quiet" onClick={()=>onTry(c)}>看大字效果 <ArrowRight/></button></div></article>)}</div></section>):
 <><p className="note-box">当前默认：小艺。这里记录选型偏好，暂不改变新版朗读；选定后统一接入。以下同一身份使用同一句台词，方便比较。小晓的两档是同一声线、不同语速和音高；人物身份只是演示角色，声音均为合成。</p>{['narrator','granddaughter','son'].map(role=>{const group=voices.filter(v=>v.role===role);return <section key={role} className="selection-group"><h2>{group[0]?.roleLabel||role}</h2><p className="sample-line">“{group[0]?.text}”</p><div className="candidate-grid">{group.map((v,i)=><article key={v.id} className={'candidate voice-candidate '+(selection.voices[role]===v.id?'chosen':'')}><b className="voice-number">{['A','B','C'][i]}</b><h3>{v.name}</h3><p>{v.description}</p><p className="fine">{v.language} · 合成声音</p><audio controls src={v.url} preload="none" onPlay={e=>document.querySelectorAll('audio').forEach(a=>{if(a!==e.currentTarget)a.pause();})}/><button className="primary" aria-pressed={selection.voices[role]===v.id} onClick={()=>choose('voices',role,v.id)}>{selection.voices[role]===v.id?<><Check/>已选这版</>:'选这版声音'}</button></article>)}</div></section>;})}</>}
 <div className="choice-summary"><strong>本机已选</strong><span>{Object.values(selection.cases).join(' · ')||'案例还没选'}</span><span>{Object.values(selection.voices).map(id=>voices.find(v=>v.id===id)?.name).filter(Boolean).join(' · ')||'声音暂沿用小艺'}</span><button className="secondary" onClick={onBack}>回到新版体验</button></div>
 </div>;
}
